export const LOAD_VASES = 'LOAD_VASES';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const UPDATE_TOTAL_ORDER = 'UPDATE_TOTAL_ORDER';
